services:
  db:
    image: 'postgres:17'
    container_name: 'duilio'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=duilio
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
